// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/EwanGreer/chatatui/internal/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMessageStore creates a new instance of MockMessageStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessageStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessageStore {
	mock := &MockMessageStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMessageStore is an autogenerated mock type for the MessageStore type
type MockMessageStore struct {
	mock.Mock
}

type MockMessageStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessageStore) EXPECT() *MockMessageStore_Expecter {
	return &MockMessageStore_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockMessageStore
func (_mock *MockMessageStore) Create(msg *domain.Message) error {
	ret := _mock.Called(msg)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*domain.Message) error); ok {
		r0 = returnFunc(msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMessageStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockMessageStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - msg *domain.Message
func (_e *MockMessageStore_Expecter) Create(msg interface{}) *MockMessageStore_Create_Call {
	return &MockMessageStore_Create_Call{Call: _e.mock.On("Create", msg)}
}

func (_c *MockMessageStore_Create_Call) Run(run func(msg *domain.Message)) *MockMessageStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *domain.Message
		if args[0] != nil {
			arg0 = args[0].(*domain.Message)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMessageStore_Create_Call) Return(err error) *MockMessageStore_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMessageStore_Create_Call) RunAndReturn(run func(msg *domain.Message) error) *MockMessageStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByRoom provides a mock function for the type MockMessageStore
func (_mock *MockMessageStore) GetByRoom(roomID uuid.UUID, limit int, offset int) ([]domain.Message, error) {
	ret := _mock.Called(roomID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetByRoom")
	}

	var r0 []domain.Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, int, int) ([]domain.Message, error)); ok {
		return returnFunc(roomID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, int, int) []domain.Message); ok {
		r0 = returnFunc(roomID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Message)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID, int, int) error); ok {
		r1 = returnFunc(roomID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMessageStore_GetByRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByRoom'
type MockMessageStore_GetByRoom_Call struct {
	*mock.Call
}

// GetByRoom is a helper method to define mock.On call
//   - roomID uuid.UUID
//   - limit int
//   - offset int
func (_e *MockMessageStore_Expecter) GetByRoom(roomID interface{}, limit interface{}, offset interface{}) *MockMessageStore_GetByRoom_Call {
	return &MockMessageStore_GetByRoom_Call{Call: _e.mock.On("GetByRoom", roomID, limit, offset)}
}

func (_c *MockMessageStore_GetByRoom_Call) Run(run func(roomID uuid.UUID, limit int, offset int)) *MockMessageStore_GetByRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMessageStore_GetByRoom_Call) Return(messages []domain.Message, err error) *MockMessageStore_GetByRoom_Call {
	_c.Call.Return(messages, err)
	return _c
}

func (_c *MockMessageStore_GetByRoom_Call) RunAndReturn(run func(roomID uuid.UUID, limit int, offset int) ([]domain.Message, error)) *MockMessageStore_GetByRoom_Call {
	_c.Call.Return(run)
	return _c
}
