// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/EwanGreer/chatatui/internal/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRoomStore creates a new instance of MockRoomStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoomStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoomStore {
	mock := &MockRoomStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRoomStore is an autogenerated mock type for the RoomStore type
type MockRoomStore struct {
	mock.Mock
}

type MockRoomStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoomStore) EXPECT() *MockRoomStore_Expecter {
	return &MockRoomStore_Expecter{mock: &_m.Mock}
}

// AddMember provides a mock function for the type MockRoomStore
func (_mock *MockRoomStore) AddMember(roomID uuid.UUID, userID uuid.UUID) error {
	ret := _mock.Called(roomID, userID)

	if len(ret) == 0 {
		panic("no return value specified for AddMember")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(roomID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRoomStore_AddMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddMember'
type MockRoomStore_AddMember_Call struct {
	*mock.Call
}

// AddMember is a helper method to define mock.On call
//   - roomID uuid.UUID
//   - userID uuid.UUID
func (_e *MockRoomStore_Expecter) AddMember(roomID interface{}, userID interface{}) *MockRoomStore_AddMember_Call {
	return &MockRoomStore_AddMember_Call{Call: _e.mock.On("AddMember", roomID, userID)}
}

func (_c *MockRoomStore_AddMember_Call) Run(run func(roomID uuid.UUID, userID uuid.UUID)) *MockRoomStore_AddMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRoomStore_AddMember_Call) Return(err error) *MockRoomStore_AddMember_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRoomStore_AddMember_Call) RunAndReturn(run func(roomID uuid.UUID, userID uuid.UUID) error) *MockRoomStore_AddMember_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockRoomStore
func (_mock *MockRoomStore) GetByID(id uuid.UUID) (*domain.Room, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Room
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (*domain.Room, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) *domain.Room); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Room)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoomStore_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockRoomStore_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockRoomStore_Expecter) GetByID(id interface{}) *MockRoomStore_GetByID_Call {
	return &MockRoomStore_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *MockRoomStore_GetByID_Call) Run(run func(id uuid.UUID)) *MockRoomStore_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRoomStore_GetByID_Call) Return(room *domain.Room, err error) *MockRoomStore_GetByID_Call {
	_c.Call.Return(room, err)
	return _c
}

func (_c *MockRoomStore_GetByID_Call) RunAndReturn(run func(id uuid.UUID) (*domain.Room, error)) *MockRoomStore_GetByID_Call {
	_c.Call.Return(run)
	return _c
}
