// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/EwanGreer/chatatui/internal/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockChatService creates a new instance of MockChatService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatService {
	mock := &MockChatService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChatService is an autogenerated mock type for the ChatService type
type MockChatService struct {
	mock.Mock
}

type MockChatService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatService) EXPECT() *MockChatService_Expecter {
	return &MockChatService_Expecter{mock: &_m.Mock}
}

// GetRoom provides a mock function for the type MockChatService
func (_mock *MockChatService) GetRoom(id uuid.UUID) (*domain.Room, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetRoom")
	}

	var r0 *domain.Room
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (*domain.Room, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) *domain.Room); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Room)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type MockChatService_GetRoom_Call struct {
	*mock.Call
}

func (_e *MockChatService_Expecter) GetRoom(id interface{}) *MockChatService_GetRoom_Call {
	return &MockChatService_GetRoom_Call{Call: _e.mock.On("GetRoom", id)}
}

func (_c *MockChatService_GetRoom_Call) Run(run func(id uuid.UUID)) *MockChatService_GetRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(arg0)
	})
	return _c
}

func (_c *MockChatService_GetRoom_Call) Return(room *domain.Room, err error) *MockChatService_GetRoom_Call {
	_c.Call.Return(room, err)
	return _c
}

func (_c *MockChatService_GetRoom_Call) RunAndReturn(run func(id uuid.UUID) (*domain.Room, error)) *MockChatService_GetRoom_Call {
	_c.Call.Return(run)
	return _c
}

// JoinRoom provides a mock function for the type MockChatService
func (_mock *MockChatService) JoinRoom(roomID uuid.UUID, userID uuid.UUID) ([]domain.WireMessage, error) {
	ret := _mock.Called(roomID, userID)

	if len(ret) == 0 {
		panic("no return value specified for JoinRoom")
	}

	var r0 []domain.WireMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) ([]domain.WireMessage, error)); ok {
		return returnFunc(roomID, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) []domain.WireMessage); ok {
		r0 = returnFunc(roomID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.WireMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(roomID, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type MockChatService_JoinRoom_Call struct {
	*mock.Call
}

func (_e *MockChatService_Expecter) JoinRoom(roomID interface{}, userID interface{}) *MockChatService_JoinRoom_Call {
	return &MockChatService_JoinRoom_Call{Call: _e.mock.On("JoinRoom", roomID, userID)}
}

func (_c *MockChatService_JoinRoom_Call) Run(run func(roomID uuid.UUID, userID uuid.UUID)) *MockChatService_JoinRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(arg0, arg1)
	})
	return _c
}

func (_c *MockChatService_JoinRoom_Call) Return(messages []domain.WireMessage, err error) *MockChatService_JoinRoom_Call {
	_c.Call.Return(messages, err)
	return _c
}

func (_c *MockChatService_JoinRoom_Call) RunAndReturn(run func(uuid.UUID, uuid.UUID) ([]domain.WireMessage, error)) *MockChatService_JoinRoom_Call {
	_c.Call.Return(run)
	return _c
}

// PublishMessage provides a mock function for the type MockChatService
func (_mock *MockChatService) PublishMessage(content []byte, senderID uuid.UUID, senderName string, roomID uuid.UUID) (*domain.WireMessage, error) {
	ret := _mock.Called(content, senderID, senderName, roomID)

	if len(ret) == 0 {
		panic("no return value specified for PublishMessage")
	}

	var r0 *domain.WireMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte, uuid.UUID, string, uuid.UUID) (*domain.WireMessage, error)); ok {
		return returnFunc(content, senderID, senderName, roomID)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte, uuid.UUID, string, uuid.UUID) *domain.WireMessage); ok {
		r0 = returnFunc(content, senderID, senderName, roomID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.WireMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte, uuid.UUID, string, uuid.UUID) error); ok {
		r1 = returnFunc(content, senderID, senderName, roomID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

type MockChatService_PublishMessage_Call struct {
	*mock.Call
}

func (_e *MockChatService_Expecter) PublishMessage(content interface{}, senderID interface{}, senderName interface{}, roomID interface{}) *MockChatService_PublishMessage_Call {
	return &MockChatService_PublishMessage_Call{Call: _e.mock.On("PublishMessage", content, senderID, senderName, roomID)}
}

func (_c *MockChatService_PublishMessage_Call) Run(run func(content []byte, senderID uuid.UUID, senderName string, roomID uuid.UUID)) *MockChatService_PublishMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		run(arg0, arg1, arg2, arg3)
	})
	return _c
}

func (_c *MockChatService_PublishMessage_Call) Return(msg *domain.WireMessage, err error) *MockChatService_PublishMessage_Call {
	_c.Call.Return(msg, err)
	return _c
}

func (_c *MockChatService_PublishMessage_Call) RunAndReturn(run func([]byte, uuid.UUID, string, uuid.UUID) (*domain.WireMessage, error)) *MockChatService_PublishMessage_Call {
	_c.Call.Return(run)
	return _c
}
