// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	"github.com/egreerdp/chatatui/internal/service"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockChatService creates a new instance of MockChatService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatService {
	mock := &MockChatService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChatService is an autogenerated mock type for the ChatService type
type MockChatService struct {
	mock.Mock
}

type MockChatService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatService) EXPECT() *MockChatService_Expecter {
	return &MockChatService_Expecter{mock: &_m.Mock}
}

// AddRoomMember provides a mock function for the type MockChatService
func (_mock *MockChatService) AddRoomMember(roomID uuid.UUID, userID uuid.UUID) error {
	ret := _mock.Called(roomID, userID)

	if len(ret) == 0 {
		panic("no return value specified for AddRoomMember")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(roomID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChatService_AddRoomMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddRoomMember'
type MockChatService_AddRoomMember_Call struct {
	*mock.Call
}

// AddRoomMember is a helper method to define mock.On call
//   - roomID uuid.UUID
//   - userID uuid.UUID
func (_e *MockChatService_Expecter) AddRoomMember(roomID interface{}, userID interface{}) *MockChatService_AddRoomMember_Call {
	return &MockChatService_AddRoomMember_Call{Call: _e.mock.On("AddRoomMember", roomID, userID)}
}

func (_c *MockChatService_AddRoomMember_Call) Run(run func(roomID uuid.UUID, userID uuid.UUID)) *MockChatService_AddRoomMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockChatService_AddRoomMember_Call) Return(err error) *MockChatService_AddRoomMember_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChatService_AddRoomMember_Call) RunAndReturn(run func(roomID uuid.UUID, userID uuid.UUID) error) *MockChatService_AddRoomMember_Call {
	_c.Call.Return(run)
	return _c
}

// GetMessageHistory provides a mock function for the type MockChatService
func (_mock *MockChatService) GetMessageHistory(roomID uuid.UUID, limit int, offset int) ([]service.MessageInfo, error) {
	ret := _mock.Called(roomID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetMessageHistory")
	}

	var r0 []service.MessageInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, int, int) ([]service.MessageInfo, error)); ok {
		return returnFunc(roomID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, int, int) []service.MessageInfo); ok {
		r0 = returnFunc(roomID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.MessageInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID, int, int) error); ok {
		r1 = returnFunc(roomID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatService_GetMessageHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessageHistory'
type MockChatService_GetMessageHistory_Call struct {
	*mock.Call
}

// GetMessageHistory is a helper method to define mock.On call
//   - roomID uuid.UUID
//   - limit int
//   - offset int
func (_e *MockChatService_Expecter) GetMessageHistory(roomID interface{}, limit interface{}, offset interface{}) *MockChatService_GetMessageHistory_Call {
	return &MockChatService_GetMessageHistory_Call{Call: _e.mock.On("GetMessageHistory", roomID, limit, offset)}
}

func (_c *MockChatService_GetMessageHistory_Call) Run(run func(roomID uuid.UUID, limit int, offset int)) *MockChatService_GetMessageHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockChatService_GetMessageHistory_Call) Return(messageInfos []service.MessageInfo, err error) *MockChatService_GetMessageHistory_Call {
	_c.Call.Return(messageInfos, err)
	return _c
}

func (_c *MockChatService_GetMessageHistory_Call) RunAndReturn(run func(roomID uuid.UUID, limit int, offset int) ([]service.MessageInfo, error)) *MockChatService_GetMessageHistory_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoom provides a mock function for the type MockChatService
func (_mock *MockChatService) GetRoom(id uuid.UUID) (*service.RoomInfo, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetRoom")
	}

	var r0 *service.RoomInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) (*service.RoomInfo, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) *service.RoomInfo); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.RoomInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatService_GetRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoom'
type MockChatService_GetRoom_Call struct {
	*mock.Call
}

// GetRoom is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *MockChatService_Expecter) GetRoom(id interface{}) *MockChatService_GetRoom_Call {
	return &MockChatService_GetRoom_Call{Call: _e.mock.On("GetRoom", id)}
}

func (_c *MockChatService_GetRoom_Call) Run(run func(id uuid.UUID)) *MockChatService_GetRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockChatService_GetRoom_Call) Return(roomInfo *service.RoomInfo, err error) *MockChatService_GetRoom_Call {
	_c.Call.Return(roomInfo, err)
	return _c
}

func (_c *MockChatService_GetRoom_Call) RunAndReturn(run func(id uuid.UUID) (*service.RoomInfo, error)) *MockChatService_GetRoom_Call {
	_c.Call.Return(run)
	return _c
}

// PersistMessage provides a mock function for the type MockChatService
func (_mock *MockChatService) PersistMessage(content []byte, senderID uuid.UUID, roomID uuid.UUID) (uuid.UUID, time.Time, error) {
	ret := _mock.Called(content, senderID, roomID)

	if len(ret) == 0 {
		panic("no return value specified for PersistMessage")
	}

	var r0 uuid.UUID
	var r1 time.Time
	var r2 error
	if returnFunc, ok := ret.Get(0).(func([]byte, uuid.UUID, uuid.UUID) (uuid.UUID, time.Time, error)); ok {
		return returnFunc(content, senderID, roomID)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte, uuid.UUID, uuid.UUID) uuid.UUID); ok {
		r0 = returnFunc(content, senderID, roomID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte, uuid.UUID, uuid.UUID) time.Time); ok {
		r1 = returnFunc(content, senderID, roomID)
	} else {
		r1 = ret.Get(1).(time.Time)
	}
	if returnFunc, ok := ret.Get(2).(func([]byte, uuid.UUID, uuid.UUID) error); ok {
		r2 = returnFunc(content, senderID, roomID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockChatService_PersistMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PersistMessage'
type MockChatService_PersistMessage_Call struct {
	*mock.Call
}

// PersistMessage is a helper method to define mock.On call
//   - content []byte
//   - senderID uuid.UUID
//   - roomID uuid.UUID
func (_e *MockChatService_Expecter) PersistMessage(content interface{}, senderID interface{}, roomID interface{}) *MockChatService_PersistMessage_Call {
	return &MockChatService_PersistMessage_Call{Call: _e.mock.On("PersistMessage", content, senderID, roomID)}
}

func (_c *MockChatService_PersistMessage_Call) Run(run func(content []byte, senderID uuid.UUID, roomID uuid.UUID)) *MockChatService_PersistMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockChatService_PersistMessage_Call) Return(uUID uuid.UUID, time1 time.Time, err error) *MockChatService_PersistMessage_Call {
	_c.Call.Return(uUID, time1, err)
	return _c
}

func (_c *MockChatService_PersistMessage_Call) RunAndReturn(run func(content []byte, senderID uuid.UUID, roomID uuid.UUID) (uuid.UUID, time.Time, error)) *MockChatService_PersistMessage_Call {
	_c.Call.Return(run)
	return _c
}
