// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/EwanGreer/chatatui/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRoomStore creates a new instance of MockRoomStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRoomStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRoomStore {
	mock := &MockRoomStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRoomStore is an autogenerated mock type for the RoomStore type
type MockRoomStore struct {
	mock.Mock
}

type MockRoomStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRoomStore) EXPECT() *MockRoomStore_Expecter {
	return &MockRoomStore_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockRoomStore
func (_mock *MockRoomStore) Create(room *repository.Room) error {
	ret := _mock.Called(room)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*repository.Room) error); ok {
		r0 = returnFunc(room)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRoomStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRoomStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - room *repository.Room
func (_e *MockRoomStore_Expecter) Create(room interface{}) *MockRoomStore_Create_Call {
	return &MockRoomStore_Create_Call{Call: _e.mock.On("Create", room)}
}

func (_c *MockRoomStore_Create_Call) Run(run func(room *repository.Room)) *MockRoomStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *repository.Room
		if args[0] != nil {
			arg0 = args[0].(*repository.Room)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRoomStore_Create_Call) Return(err error) *MockRoomStore_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRoomStore_Create_Call) RunAndReturn(run func(room *repository.Room) error) *MockRoomStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockRoomStore
func (_mock *MockRoomStore) List(limit int, offset int) ([]repository.Room, error) {
	ret := _mock.Called(limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []repository.Room
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int, int) ([]repository.Room, error)); ok {
		return returnFunc(limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(int, int) []repository.Room); ok {
		r0 = returnFunc(limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.Room)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = returnFunc(limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRoomStore_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRoomStore_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - limit int
//   - offset int
func (_e *MockRoomStore_Expecter) List(limit interface{}, offset interface{}) *MockRoomStore_List_Call {
	return &MockRoomStore_List_Call{Call: _e.mock.On("List", limit, offset)}
}

func (_c *MockRoomStore_List_Call) Run(run func(limit int, offset int)) *MockRoomStore_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRoomStore_List_Call) Return(rooms []repository.Room, err error) *MockRoomStore_List_Call {
	_c.Call.Return(rooms, err)
	return _c
}

func (_c *MockRoomStore_List_Call) RunAndReturn(run func(limit int, offset int) ([]repository.Room, error)) *MockRoomStore_List_Call {
	_c.Call.Return(run)
	return _c
}
