// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/EwanGreer/chatatui/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserStore creates a new instance of MockUserStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserStore {
	mock := &MockUserStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserStore is an autogenerated mock type for the UserStore type
type MockUserStore struct {
	mock.Mock
}

type MockUserStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserStore) EXPECT() *MockUserStore_Expecter {
	return &MockUserStore_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockUserStore
func (_mock *MockUserStore) Create(user *domain.User) error {
	ret := _mock.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*domain.User) error); ok {
		r0 = returnFunc(user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - user *domain.User
func (_e *MockUserStore_Expecter) Create(user interface{}) *MockUserStore_Create_Call {
	return &MockUserStore_Create_Call{Call: _e.mock.On("Create", user)}
}

func (_c *MockUserStore_Create_Call) Run(run func(user *domain.User)) *MockUserStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *domain.User
		if args[0] != nil {
			arg0 = args[0].(*domain.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserStore_Create_Call) Return(err error) *MockUserStore_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserStore_Create_Call) RunAndReturn(run func(user *domain.User) error) *MockUserStore_Create_Call {
	_c.Call.Return(run)
	return _c
}
