// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/EwanGreer/chatatui/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserLookup creates a new instance of MockUserLookup. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserLookup(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserLookup {
	mock := &MockUserLookup{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserLookup is an autogenerated mock type for the UserLookup type
type MockUserLookup struct {
	mock.Mock
}

type MockUserLookup_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserLookup) EXPECT() *MockUserLookup_Expecter {
	return &MockUserLookup_Expecter{mock: &_m.Mock}
}

// GetByAPIKey provides a mock function for the type MockUserLookup
func (_mock *MockUserLookup) GetByAPIKey(apiKey string) (*domain.User, error) {
	ret := _mock.Called(apiKey)

	if len(ret) == 0 {
		panic("no return value specified for GetByAPIKey")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*domain.User, error)); ok {
		return returnFunc(apiKey)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *domain.User); ok {
		r0 = returnFunc(apiKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(apiKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserLookup_GetByAPIKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByAPIKey'
type MockUserLookup_GetByAPIKey_Call struct {
	*mock.Call
}

// GetByAPIKey is a helper method to define mock.On call
//   - apiKey string
func (_e *MockUserLookup_Expecter) GetByAPIKey(apiKey interface{}) *MockUserLookup_GetByAPIKey_Call {
	return &MockUserLookup_GetByAPIKey_Call{Call: _e.mock.On("GetByAPIKey", apiKey)}
}

func (_c *MockUserLookup_GetByAPIKey_Call) Run(run func(apiKey string)) *MockUserLookup_GetByAPIKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserLookup_GetByAPIKey_Call) Return(user *domain.User, err error) *MockUserLookup_GetByAPIKey_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserLookup_GetByAPIKey_Call) RunAndReturn(run func(apiKey string) (*domain.User, error)) *MockUserLookup_GetByAPIKey_Call {
	_c.Call.Return(run)
	return _c
}
